### ISSUE TITLE
Use subpalettes in tl_settings

### ISSUE THREAD

**Issue by bennyborn** [DieSchittigs/recaptcha-bundle#10]
Hi there,

when switching to reCaptchaV3 in `tl_settings` you replace the whole default-palette with your own one. This leads to massive problems with any other extension that would be loaded after yours and tries to add some fields to the default palette.

Please use subpalettes instead.

https://github.com/DieSchittigs/recaptcha-bundle/blob/3d24354ad778e55f68552460f3b6bdaa5ffba996/src/Resources/contao/dca/tl_settings.php#L7

**Comment by bennyborn** [comment]
Is this extension still maintained? I've noticed another issue but if there is no support anymore I might go on create an own extension.

**Comment by benfolds** [comment]
Hi benny, the developer is not active right now.
Can you make a merge request? I will merge it and draft a new release.

**Comment by bennyborn** [comment]
@benfolds Done. Also fixed a small JS problem (see #15)

**Comment by Songworks** [comment]
@benfolds Several fixes were kindly supplied by @bennyborn
Could you please merge and publish them. Thanks in advance!

**Comment by Songworks** [comment]
@benfolds Could you please release the latest version for this? Contao/Packagist only has v1.2.4 as the latest version (non dev-master) available.
