### ISSUE TITLE
Auto-grid Function in form generator after installing away

### ISSUE THREAD

**Issue by astrotiger** [DieSchittigs/recaptcha-bundle#11]
I use the premium-contao-theme (https://www.premium-contao-themes.com/) which has an auto-grid system module in the package.
When I am installing this package with the contao manager, the database will be acutalized in this way, that the auto-grid system of the formular generator is away.
I see also this in the database update, after installation:
ALTER TABLE tl_form_field DROP autogrid
ALTER TABLE tl_form_field DROP autogrid_mode
ALTER TABLE tl_form_field DROP autogrid_css
ALTER TABLE tl_form_field DROP autogrid_newline
ALTER TABLE tl_form_field DROP autogrid_border
ALTER TABLE tl_form_field DROP autogrid_sameheight
ALTER TABLE tl_form_field DROP autogrid_adjust_mobile
ALTER TABLE tl_form_field DROP autogrid_no_gutter
ALTER TABLE tl_form_field DROP autogrid_margin
ALTER TABLE tl_form_field DROP addFontIcon
ALTER TABLE tl_form_field DROP fontIcon

**Comment by Songworks** [comment]
It's because of the `if (Config::get('recaptchaType') != 'recaptcha3') return;` within the `dca/tl_form_fields.php`.
Since contao combines the various DCA files into one, this prevents any dca changes after this line from other modules to take place if you are not using recaptcha3!
