### ISSUE TITLE
Fehlerhinweis für den Inhaber der Website: Schlüsseltyp ungültig.

### ISSUE THREAD

**Issue by Kyuhunter** [DieSchittigs/recaptcha-bundle#17]
Bei dem Versuch das Google Recaptcha V3 einzubinden wird der Fehler "Fehlerhinweis für den Inhaber der Website: Schlüsseltyp ungültig." im Frontend angezeigt. 
Für mich verschwindet der Fehler nach ca. 1 Sekunde wieder und ich kann das Formular wie gewohnt bedienen, allerdings berichten einige User, dass Sie die Formulare dadurch nicht abschicken können.

**Comment by bennyborn** [comment]
Nachdem uns das Problem auch einige Male reported wurde weis ich jetzt auch wieso. Der Fehler bleibt im Internet Explorer sichtbar weil das JavaScript einen Fehler wirft. Der IE kennt kein replaceWith

https://github.com/DieSchittigs/recaptcha-bundle/blob/6253da514ac0d7e0da19a9390ed3d6730ee59c63/src/Resources/contao/templates/form_recaptcha.html5#L43

Edit: Als Quickfix kann man die Zeile 43 im Template einfach durch folgende ersetzen:

```js
node.parentNode.replaceChild(input, node);
```

Ich bereite gerade noch einen PR vor.
