### ISSUE TITLE
"onSubmit_captcha_registration" not found

### ISSUE THREAD

**Issue by emha** [DieSchittigs/recaptcha-bundle#8]
When I use the V2-Invisible captcha I get this error message when submitting a form. The form doesn't get submitted when it throws the error.

`ReCAPTCHA couldn't find user-provided function: onSubmit_captcha_registration`

The V3-Captcha works fine.

**Comment by tophcodes** [comment]
Fix is included in [v1.2.4](https://github.com/DieSchittigs/recaptcha-bundle/releases/tag/v1.2.4).
